server:
  port: 80

spring:
  application:
    name: cloud-provider-hystrix-payment-service

feign:
  hystrix:
    enabled: true

ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 2000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://localhost:7001/eureka/
